### ISSUE TITLE
What's the difference to `z.infer<typeof someSchema>`?

### ISSUE THREAD

**Issue by 205g0** [sachinraja/zod-to-ts#16]
zod already provides `z.inder`, why would I need this lib?

**Comment by sachinraja** [comment]
This package is great for build tools that accept Zod schemas. `z.infer` is on the type level, while this package builds a TS type definition just from the schema that a user might pass into a function.

If you're doing type inference, use `z.infer`. If you're trying to emit the types from a Zod schema, then use this package.

**Comment by 205g0** [comment]
Just skimmed your readme again. don't they do exactly the same? Would you mind to elaborate with an example? Highly appreciated and might be also good to have this clarification on you readme.

**Comment by sachinraja** [comment]
Here's an example of a project that uses this package to generate client-side types: https://github.com/sachinraja/trpc-playground. It creates a playground for [tRPC](https://trpc.io/) users to query their API in the browser. There's no way to do runtime type inference in the browser from local files. So it uses `zod-to-ts` to build the types from the Zod schema and send them to tsserver running in the browser.
