### ISSUE TITLE
Typescript should be regular dependency

### ISSUE THREAD

**Issue by RobinTail** [sachinraja/zod-to-ts#23]
Hello @sachinraja ,

After upgrading to TS 4.9, which is specified as a peer dependency of your library, I noticed the following warnings:

```
DeprecationWarning: 'createTypeAliasDeclaration' has been deprecated since v4.8.0. Decorators are no longer supported for this function. Callers should switch to an overload that does not accept a 'decorators' parameter.

    > 56 |         const inputAlias = createTypeAlias( ... );

DeprecationWarning: 'createParameterDeclaration' has been deprecated since v4.8.0. Decorators have been combined with modifiers. Callers should switch to an overload that does not accept a 'decorators' parameter.

    > 49 |         const response = zodToTs( ... );

DeprecationWarning: 'createIndexSignature' has been deprecated since v4.8.0. Decorators are no longer supported for this function. Callers should switch to an overload that does not accept a 'decorators' parameter.

    > 49 |         const response = zodToTs( ... );
```

Since you're operating the TS' factory methods that are subject for changes, I believe that Typescript should be the regular dependency of the package, not dev+peer. Thus, your implementation would operate the exact version of Typescript that is needed.

I'm going to create a PR for this.

**Comment by sachinraja** [comment]
Hey, thanks for opening this! I'm still not sure if I want to move it from a peer dependency though. What happens if TS implements a new operator like `satisfies`? Would I also have to keep that version updated here and do a new release?

I'm ok with doing that but it doesn't feel right. It might be necessary though since TS doesn't follow semver.

**Comment by RobinTail** [comment]
Hello @sachinraja ,

TS already released `satisfies` in 4.9.
However, as longer as you don't need to use it, you don't have to update Typescript dependency of your library.

Moreover, consumers of your library, having their own TS 4.9 wouldn't see the warning I mentioned above, since your library would have it's own TS 4.8.4 version installed (as a sub-dependency need for that particular purpose).

And the final piece. When TS 5.0 will be released, having some breaking changes and removed methods, your library would remain operational, since it would still operate the version defined in prod dependencies. It will for those who'll be using TS 5 in their project as well.

So, in general and regarding Typescript, I see this approach more beneficial.
I'm going to do this in `express-zod-api`, since I found the same problem.
However, consider this as just a suggestion and my humble opinion.

Best wishes.

**Comment by RobinTail** [comment]
@sachinraja ,

what would be your decision on this and #24 ?

**Comment by sachinraja** [comment]
I'm leaning on no for this @RobinTail. I don't like forcing the consumer to use our version of TypeScript. I'd rather use stricter peer dependencies to enforce a certain version. In almost every project I use `zod-to-ts` in, I don't want it to have its own version of TypeScript.

**Comment by RobinTail** [comment]
@sachinraja ,

By making Typescript a prod dependency you do not affect the version of Typescript on consumer's side.
Consumer's Typescript is installed to `/node_modules/typescript`, while Typescript used by your package (used by consumer) is installed to `/node_modules/zod-to-ts/node_modules/typescript`.
So they are completely independent installations.

However, if what I've said doesn't sound convincing enough, please close this issue so I'd know what final decision you ended up making, as I need to make mine.

**Comment by RobinTail** [comment]
@sachinraja 

> I don't like forcing the consumer to use our version of TypeScript. 

and

> I'd rather use stricter peer dependencies to enforce a certain version

these two statements contradict each other.
peer dependency — IS forcing the consumer to use certain TS version.

While I'm offering to have your own TS version installed for your package needs.
