### ISSUE TITLE
Have the option to deeply include zod descriptions as jsdoc comments

### ISSUE THREAD

**Issue by williampayne23** [sachinraja/zod-to-ts#31]
Currently you can easily add a jsdoc comment in createTypeAlias but not for deeply nested schemas (e.g to document all properties of an interface)

**Comment by j-murata** [comment]
FYI:
```js
import { printNode, zodToTs } from 'zod-to-ts';

const { node } = zodToTs(schema, name);
printNode(node, { removeComments: false });
```
https://github.com/sachinraja/zod-to-ts/blob/8fe9eaa4cd2073b2ef412ade0f403fa765dd7fc2/src/utils.ts#L34

**Comment by sachinraja** [comment]
If you use [.describe()](https://zod.dev/?id=describe) it will be automatically added as JSDoc comments on those properties.
